### PR TITLE
Delete and gitignore yarn.lock files

### PR DESCRIPTION
**Pull request by cnunciato**

### CODE REVIEW

**Comment by cnunciato** [comment]
@justinvp Noticed a couple of these files snuck in here. Do you know if deleting and git-ignoring them is a safe thing to do now, or should we wait until a release containing https://github.com/pulumi/pulumi/issues/11121 goes out?

**Comment by justinvp** [comment]
It’ll likely be ok, but let me try it out in a test repo first. Should be able to get to it tomorrow.

**Review by justinvp — APPROVED** [review]
LGTM

I tried this out in a test repo and it should be fine for all CLIs

**Comment by cnunciato** [comment]
Excellent, thank you Justin!

**Pull request merged**
