### PR TITLE
Delete .DS_Store

### PR DESCRIPTION
**Pull request by cnunciato**
Just happened to notice this and assumed it was me. 😄

### CODE REVIEW

**Review by susanev — APPROVED** [review]

**Comment by mikhailshilkov** [comment]
Should we add it to gitignore?

**Comment by cnunciato** [comment]
Added that @mikhailshilkov. Am I good to merge this otherwise? Or do I need to do something else to make these tests pass first?

**Comment by mikhailshilkov** [comment]
@cnunciato I think the failures are unrelated - @stack72 looks like Azure auth failures again?

**Comment by cnunciato** [comment]
I'll merge then. Thanks folks!

**Pull request merged**
