### PR TITLE
Update K8s version on AZ templates.

### PR DESCRIPTION
**Pull request by jkodroff**
Looks like 1.24 is no longer supported, at least in westus2.

### CODE REVIEW

**Comment by scottslowe** [comment]
@jkodroff This is great, thank you! One small request: would you mind just removing the patch version entirely? Per the docs, it should then select the latest supported patch release for the specified `major.minor` version. That'll be one less thing we need to track/change regularly.

**Comment by jkodroff** [comment]
I also `.gitignored` `.gradle` at the top level b/c VS Code was creating it automatically. (Did not add it at the template level because I don't know Gradle and it may be desirable to keep it under version control.)

**Comment by jkodroff** [comment]
Per convo with @scottslowe, we're gonna omit the version entirely which will give us CURRENT_PROD_VERSION - 1, which will significantly reduce the maintenance burden for the template.

**Pull request closed without merging**
