### PR TITLE
Fix Google Cloud auth step for CI

### PR DESCRIPTION
**Pull request by lblackstone**
The checkout step on the performance cron was out of order, so the credentials were being overwritten during this process.

### CODE REVIEW

**Comment by cnunciato** [comment]
@t0yv0 mind taking a look here? This change seems like it may now be causing all tests to fail: https://github.com/pulumi/templates/actions/runs/3128661109 (Apologies if I'm reading this wrong, though -- new to this repo.)

**Comment by t0yv0** [comment]
Something is definitely going off the rails but I don't think it's this change.

I see this which seems like a "random" hash collision:

```

environments.go:48
error: 'test-env200695551' is not a valid project name. A project with this name already exists
 environments.go:62:


azure-classic-yaml failed
no Pulumi.yaml project file found (searching upwards from ). If you have not created a project yet, use `pulumi new` to do so
panic: fatal: A precondition has failed for path
```

And then I also see this in subsequent failures:

```
tee: /tmp/gotest.log: No space left on device
```

**Comment by cnunciato** [comment]
> `No space left on device`

Awesome, thanks for spotting this! I noticed it last night also and wondered if there was something to it. Thanks for the follow-up change! 🤞

**Comment by t0yv0** [comment]
Let's see if this restores it to green, maybe more work is needed.

**Pull request merged**
