### PR TITLE
Add a Java JBang template

### PR DESCRIPTION
**Pull request by t0yv0**

### CODE REVIEW

**Review by iwahbe — APPROVED** [review]

**Comment by RobbieMcKinstry** [comment]
Do these templates always show up when calling `pulumi new`? I saw some templates in this repo that did not appear in the CLI search.

**Comment by t0yv0** [comment]
Yes. Which ones? I've just tested `pulumi new java-jbang` and it worked for me. Also:

```
pulumi new --help | grep java-                                                                                                                         ~/tmp/a2
  java-gradle                  A minimal Java Pulumi program with Gradle builds
  java-jbang                   A minimal Java Pulumi program with JBang
```

**Comment by RobbieMcKinstry** [comment]
The DigitalOcean templates didn't appear for me when I was working on my experience report (I suppose I should have included that in my report! I forgot. Whoops!)

**Comment by t0yv0** [comment]
Weird, I can't repro - seems to work for me:

```
pulumi new --help | grep digital                                ~/tmp/grpc-interceptors
  digitalocean-go              A minimal DigitalOcean Go Pulumi program
  digitalocean-javascript      A minimal DigitalOcean JavaScript Pulumi program
  digitalocean-python          A minimal DigitalOcean Python Pulumi program
  digitalocean-typescript      A minimal DigitalOcean TypeScript Pulumi program
  digitalocean-yaml            A minimal DigitalOcean Pulumi YAML program
```

**Comment by RobbieMcKinstry** [comment]
Huh, go figure.

**Pull request merged**
