### PR TITLE
Promote Azure Native to be the default Azure provider

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Resolve https://github.com/pulumi/templates/issues/155

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
Hmm, @stack72 it looks like tests pick up the templates from master, not from this PR?

**Comment by stack72** [comment]
> Hmm, @stack72 it looks like tests pick up the templates from master, not from this PR?

👀

**Comment by stack72** [comment]
@mikhailshilkov I can see above that your commit is [`e49cf6e` (#158)](https://github.com/pulumi/templates/pull/158/commits/e49cf6e704654c8ce0f3ccac8dc1becab13c74bd)

I can then see from the GitHub Action that it's checking out the following commit:

```
  /usr/bin/git checkout --progress --force refs/remotes/pull/158/merge
  Note: switching to 'refs/remotes/pull/158/merge'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  HEAD is now at 6d00f78 Merge e49cf6e704654c8ce0f3ccac8dc1becab13c74bd into 908cd1405db74798c518875c3cb530fd0720b18f
/usr/bin/git log -1 --format='%H'
'6d00f78fac5883e1a755e299b0427be3fe6ee169'
```

That commit `Merge e49cf6e704654c8ce0f3ccac8dc1becab13c74bd into` is your commit

**Comment by stack72** [comment]
Personally, I think handling this as 2 separate PRs may help with moving parts here:

1. Azure -> AzureClassic
2. Rename + enable Nextgen

**Comment by mikhailshilkov** [comment]
I wouldn't be able to merge a PR that just renames azure -> azure classic as it would break our getting started guide etc...

**Review by viveklak — APPROVED** [review]

**Pull request merged**
