### PR TITLE
Update kubernetes-java template

### PR DESCRIPTION
**Pull request by pawelprazak**
Adjusts the `kuberentes-java` template to work after breaking changes in https://github.com/pulumi/pulumi-kubernetes/pull/2055

### CODE REVIEW

**Comment by pawelprazak** [comment]
@t0yv0 should I rebace on `pulumi-java/main` or should the `pulumi-java/main` be updated to be in line with `master`?
right now I'm pulling in a lot unrelated changes from `master`

**Comment by pawelprazak** [comment]
@t0yv0 the request for merge: https://github.com/pulumi/templates/pull/311

**Comment by t0yv0** [comment]
Looks like the only diff after merge noise is the following. This looks expected 👍 

```
--- a/kubernetes-java/src/main/java/myproject/App.java
+++ b/kubernetes-java/src/main/java/myproject/App.java
@@ -1,15 +1,15 @@
 package myproject;
 
 import com.pulumi.Pulumi;
-import com.pulumi.kubernetes.apps_v1.Deployment;
-import com.pulumi.kubernetes.apps_v1.DeploymentArgs;
-import com.pulumi.kubernetes.apps_v1.inputs.DeploymentSpecArgs;
-import com.pulumi.kubernetes.core_v1.inputs.ContainerArgs;
-import com.pulumi.kubernetes.core_v1.inputs.ContainerPortArgs;
-import com.pulumi.kubernetes.core_v1.inputs.PodSpecArgs;
-import com.pulumi.kubernetes.core_v1.inputs.PodTemplateSpecArgs;
-import com.pulumi.kubernetes.meta_v1.inputs.LabelSelectorArgs;
-import com.pulumi.kubernetes.meta_v1.inputs.ObjectMetaArgs;
+import com.pulumi.kubernetes.apps.v1.Deployment;
+import com.pulumi.kubernetes.apps.v1.DeploymentArgs;
+import com.pulumi.kubernetes.apps.v1.inputs.DeploymentSpecArgs;
+import com.pulumi.kubernetes.core.v1.inputs.ContainerArgs;
+import com.pulumi.kubernetes.core.v1.inputs.ContainerPortArgs;
+import com.pulumi.kubernetes.core.v1.inputs.PodSpecArgs;
+import com.pulumi.kubernetes.core.v1.inputs.PodTemplateSpecArgs;
+import com.pulumi.kubernetes.meta.v1.inputs.LabelSelectorArgs;
+import com.pulumi.kubernetes.meta.v1.inputs.ObjectMetaArgs;
 
 import java.util.Map;
 ```

**Review by t0yv0 — APPROVED** [review]

**Comment by mikhailshilkov** [comment]
@t0yv0 I think we need to merge this?

**Pull request merged**
