### PR TITLE
feat: Kubernetes on OVH with go SDK

### PR DESCRIPTION
**Pull request by yodamad**
Adding a template to help deploying a Kubernetes cluster on OVH with the Go SDK

Inspired from [my article](https://yodamad.hashnode.dev/setup-your-kubernetes-cluster-on-ovh-with-pulumi)

Tested on Gitpod

### CODE REVIEW

**Review by scraly — COMMENTED** [review]
Little remarks :)

**Comment by yodamad** [comment]
@scraly thank you for the feedbacks, it's fixed 😉

**Comment by yodamad** [comment]
@scraly do you know some that can merge (or not) my PR ?

**Review by scraly — APPROVED** [review]

**Comment by scottslowe** [comment]
@dirien Can you take a look at this? Thank you!

**Comment by dirien** [comment]
Hi @yodamad, 

Awesome and thanks for the contribution, as discussed on Twitter/X please create a PR in the examples directory. The template repo is for (all languages if possible) very flat projects with only or two resources of the cloud or SaaS service.

For more complex or extensive examples we have the [example](https://github.com/pulumi/examples) repos.

Many thanks.

**Pull request closed without merging**
