### PR TITLE
Update templates to use BucketV2

### PR DESCRIPTION
**Pull request by t0yv0**
Adopting our own best-practice recommendation per https://github.com/pulumi/home/issues/3632

### CODE REVIEW

**Comment by t0yv0** [comment]
Reminder to self: before merging verify that Update static-website-* is covered by tests or test manually.

**Review by mjeffryes — APPROVED** [review]
TIL we have an f# aws template

**Comment by t0yv0** [comment]
Some test failures are pertinent. I'll iterate here a bit.

**Comment by t0yv0** [comment]
Still a bit more work here, will finish out on Monday.

**Pull request merged**
