### PR TITLE
chore: bump from node v14 to v16

### PR DESCRIPTION
**Pull request by simenandre**

### CODE REVIEW

**Comment by stack72** [comment]
Please view the results of the PR Build [Here][1]

[1]: https://github.com/pulumi/templates/actions/runs/1413747417

**Comment by cobraz** [comment]
Should we get this landed soon? Node v14 is now in maintainance, and node v18 will be LTS in late august.

I think we should try to update so templates follow the latest LTS, this pull request will do that.

**Comment by cnunciato** [comment]
@cobraz Sorry we didn't get to this sooner! We'll be bumping all Node templates past 16 shortly, so we should probably close this.

**Pull request closed without merging**
